package com.clearing.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
// import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.clearing.entity.TradeEntity;
import com.clearing.json.Trade;
import com.clearing.repository.TradeRepository;
import com.clearing.service.TradeService;
import com.clearing.service.TradeServiceImpl;

// import com.clearing.Settle;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/trades") // This means URL's start with /demo (after Application path)
public class TradeController {
	@Autowired // This means to get the bean called tradeRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TradeRepository tradeRepository;

	@Autowired
	private TradeService tradeService;

	// Generate Random Trades
	@GetMapping(path = "/generate")
	public @ResponseBody List<TradeEntity> generateTrades() {
		return tradeService.generateTrades();
	}

	// Fetch All Trades
	@GetMapping(path = "/allTrades")
	public @ResponseBody List<Trade> getAllTrades() {
		return tradeService.getAllTrades();
	}

	// Add Random Trades
	@GetMapping(path = "/addRandom") // Later add Parameter
	public @ResponseBody void addRandomTrade() {
		// This returns a JSON or XML with the
		int numTrades = 5; // For now
		ArrayList<TradeEntity> randomTrades = new ArrayList<TradeEntity>();

		for (int i = 0; i < numTrades; ++i) {
			randomTrades.add(new TradeEntity());
		}
		tradeRepository.saveAll(randomTrades);
	}

	// Fetch all trades in json
	@GetMapping(path = "/fetch")
	public @ResponseBody Iterable<TradeEntity> getAllUsers() {
		return tradeRepository.findAll();
	}

	// Settle Trades
	@GetMapping(path = "/settle") // Check for specific argument to ask
	public @ResponseBody void settleTrades() {
		// Basic Settling Algorithms
		// Member[] members = memberRepository.findAll();
	}

	@GetMapping("/id/{CMId}")
	public @ResponseBody List<Trade> getTradesById(@PathVariable("CMId") int CMId) {
		return tradeService.getTradesById(CMId);
	}

}
